//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartClass.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("smartClass.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 L0039 的本地化字符串。
        /// </summary>
        public static string 万满意 {
            get {
                return ResourceManager.GetString("万满意", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0007 的本地化字符串。
        /// </summary>
        public static string 何丽 {
            get {
                return ResourceManager.GetString("何丽", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0169 的本地化字符串。
        /// </summary>
        public static string 何云云 {
            get {
                return ResourceManager.GetString("何云云", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0091 的本地化字符串。
        /// </summary>
        public static string 何兴文 {
            get {
                return ResourceManager.GetString("何兴文", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0120 的本地化字符串。
        /// </summary>
        public static string 何晶晶 {
            get {
                return ResourceManager.GetString("何晶晶", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0014 的本地化字符串。
        /// </summary>
        public static string 何群 {
            get {
                return ResourceManager.GetString("何群", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0011 的本地化字符串。
        /// </summary>
        public static string 余鹏云 {
            get {
                return ResourceManager.GetString("余鹏云", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0112 的本地化字符串。
        /// </summary>
        public static string 储成林 {
            get {
                return ResourceManager.GetString("储成林", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0031 的本地化字符串。
        /// </summary>
        public static string 刘婧 {
            get {
                return ResourceManager.GetString("刘婧", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0167 的本地化字符串。
        /// </summary>
        public static string 刘悦 {
            get {
                return ResourceManager.GetString("刘悦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0029 的本地化字符串。
        /// </summary>
        public static string 刘梦雅 {
            get {
                return ResourceManager.GetString("刘梦雅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0144 的本地化字符串。
        /// </summary>
        public static string 刘洋 {
            get {
                return ResourceManager.GetString("刘洋", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0003 的本地化字符串。
        /// </summary>
        public static string 刘燕 {
            get {
                return ResourceManager.GetString("刘燕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0023 的本地化字符串。
        /// </summary>
        public static string 刘继慧 {
            get {
                return ResourceManager.GetString("刘继慧", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0147 的本地化字符串。
        /// </summary>
        public static string 刘颖 {
            get {
                return ResourceManager.GetString("刘颖", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0168 的本地化字符串。
        /// </summary>
        public static string 史贤慧 {
            get {
                return ResourceManager.GetString("史贤慧", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0047 的本地化字符串。
        /// </summary>
        public static string 叶子良 {
            get {
                return ResourceManager.GetString("叶子良", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0056 的本地化字符串。
        /// </summary>
        public static string 吕静 {
            get {
                return ResourceManager.GetString("吕静", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0018 的本地化字符串。
        /// </summary>
        public static string 吴明 {
            get {
                return ResourceManager.GetString("吴明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0140 的本地化字符串。
        /// </summary>
        public static string 吴芳 {
            get {
                return ResourceManager.GetString("吴芳", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0175 的本地化字符串。
        /// </summary>
        public static string 吴蒙梦 {
            get {
                return ResourceManager.GetString("吴蒙梦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0083 的本地化字符串。
        /// </summary>
        public static string 吴道凤 {
            get {
                return ResourceManager.GetString("吴道凤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0019 的本地化字符串。
        /// </summary>
        public static string 吴金晶 {
            get {
                return ResourceManager.GetString("吴金晶", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0026 的本地化字符串。
        /// </summary>
        public static string 周真 {
            get {
                return ResourceManager.GetString("周真", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0176 的本地化字符串。
        /// </summary>
        public static string 唐奇 {
            get {
                return ResourceManager.GetString("唐奇", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0135 的本地化字符串。
        /// </summary>
        public static string 唐思琪 {
            get {
                return ResourceManager.GetString("唐思琪", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0004 的本地化字符串。
        /// </summary>
        public static string 唐木遥 {
            get {
                return ResourceManager.GetString("唐木遥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0001 的本地化字符串。
        /// </summary>
        public static string 唐鹤明 {
            get {
                return ResourceManager.GetString("唐鹤明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0152 的本地化字符串。
        /// </summary>
        public static string 夏刘勤 {
            get {
                return ResourceManager.GetString("夏刘勤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0123 的本地化字符串。
        /// </summary>
        public static string 姚艳 {
            get {
                return ResourceManager.GetString("姚艳", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0171 的本地化字符串。
        /// </summary>
        public static string 姚莹 {
            get {
                return ResourceManager.GetString("姚莹", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0068 的本地化字符串。
        /// </summary>
        public static string 孙德勇 {
            get {
                return ResourceManager.GetString("孙德勇", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0040 的本地化字符串。
        /// </summary>
        public static string 孙梅 {
            get {
                return ResourceManager.GetString("孙梅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0055 的本地化字符串。
        /// </summary>
        public static string 孙浩泉 {
            get {
                return ResourceManager.GetString("孙浩泉", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0070 的本地化字符串。
        /// </summary>
        public static string 季海燕 {
            get {
                return ResourceManager.GetString("季海燕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0173 的本地化字符串。
        /// </summary>
        public static string 宋佳佳 {
            get {
                return ResourceManager.GetString("宋佳佳", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0125 的本地化字符串。
        /// </summary>
        public static string 宋孝华 {
            get {
                return ResourceManager.GetString("宋孝华", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0041 的本地化字符串。
        /// </summary>
        public static string 完月 {
            get {
                return ResourceManager.GetString("完月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0027 的本地化字符串。
        /// </summary>
        public static string 宣秋艳 {
            get {
                return ResourceManager.GetString("宣秋艳", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0071 的本地化字符串。
        /// </summary>
        public static string 庞岩 {
            get {
                return ResourceManager.GetString("庞岩", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0073 的本地化字符串。
        /// </summary>
        public static string 张仲强 {
            get {
                return ResourceManager.GetString("张仲强", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0058 的本地化字符串。
        /// </summary>
        public static string 张佳璇 {
            get {
                return ResourceManager.GetString("张佳璇", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0103 的本地化字符串。
        /// </summary>
        public static string 张咏梅 {
            get {
                return ResourceManager.GetString("张咏梅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0104 的本地化字符串。
        /// </summary>
        public static string 张小梅 {
            get {
                return ResourceManager.GetString("张小梅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0033 的本地化字符串。
        /// </summary>
        public static string 张巧云 {
            get {
                return ResourceManager.GetString("张巧云", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0045 的本地化字符串。
        /// </summary>
        public static string 张庆姐 {
            get {
                return ResourceManager.GetString("张庆姐", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0099 的本地化字符串。
        /// </summary>
        public static string 张旭 {
            get {
                return ResourceManager.GetString("张旭", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0119 的本地化字符串。
        /// </summary>
        public static string 张晴虹 {
            get {
                return ResourceManager.GetString("张晴虹", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0159 的本地化字符串。
        /// </summary>
        public static string 张迎 {
            get {
                return ResourceManager.GetString("张迎", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0054 的本地化字符串。
        /// </summary>
        public static string 张长武 {
            get {
                return ResourceManager.GetString("张长武", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0130 的本地化字符串。
        /// </summary>
        public static string 张青 {
            get {
                return ResourceManager.GetString("张青", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0012 的本地化字符串。
        /// </summary>
        public static string 徐亭亭 {
            get {
                return ResourceManager.GetString("徐亭亭", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0117 的本地化字符串。
        /// </summary>
        public static string 徐宏光 {
            get {
                return ResourceManager.GetString("徐宏光", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0006 的本地化字符串。
        /// </summary>
        public static string 徐玲玲 {
            get {
                return ResourceManager.GetString("徐玲玲", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0053 的本地化字符串。
        /// </summary>
        public static string 徐长华 {
            get {
                return ResourceManager.GetString("徐长华", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0143 的本地化字符串。
        /// </summary>
        public static string 方怡娟 {
            get {
                return ResourceManager.GetString("方怡娟", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0166 的本地化字符串。
        /// </summary>
        public static string 方雅丽 {
            get {
                return ResourceManager.GetString("方雅丽", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0032 的本地化字符串。
        /// </summary>
        public static string 昂月 {
            get {
                return ResourceManager.GetString("昂月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0050 的本地化字符串。
        /// </summary>
        public static string 易志忠 {
            get {
                return ResourceManager.GetString("易志忠", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0107 的本地化字符串。
        /// </summary>
        public static string 曹璐璐 {
            get {
                return ResourceManager.GetString("曹璐璐", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0122 的本地化字符串。
        /// </summary>
        public static string 朱宝莹 {
            get {
                return ResourceManager.GetString("朱宝莹", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0022 的本地化字符串。
        /// </summary>
        public static string 朱晓妹 {
            get {
                return ResourceManager.GetString("朱晓妹", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0116 的本地化字符串。
        /// </summary>
        public static string 李安梅 {
            get {
                return ResourceManager.GetString("李安梅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0158 的本地化字符串。
        /// </summary>
        public static string 李星星 {
            get {
                return ResourceManager.GetString("李星星", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0150 的本地化字符串。
        /// </summary>
        public static string 李波 {
            get {
                return ResourceManager.GetString("李波", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0065 的本地化字符串。
        /// </summary>
        public static string 李菊荣 {
            get {
                return ResourceManager.GetString("李菊荣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0087 的本地化字符串。
        /// </summary>
        public static string 杨亭 {
            get {
                return ResourceManager.GetString("杨亭", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0013 的本地化字符串。
        /// </summary>
        public static string 杨帆 {
            get {
                return ResourceManager.GetString("杨帆", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0076 的本地化字符串。
        /// </summary>
        public static string 杨海霞 {
            get {
                return ResourceManager.GetString("杨海霞", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0042 的本地化字符串。
        /// </summary>
        public static string 杨磊 {
            get {
                return ResourceManager.GetString("杨磊", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0172 的本地化字符串。
        /// </summary>
        public static string 杨红 {
            get {
                return ResourceManager.GetString("杨红", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0142 的本地化字符串。
        /// </summary>
        public static string 杨语妍 {
            get {
                return ResourceManager.GetString("杨语妍", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0038 的本地化字符串。
        /// </summary>
        public static string 柳艳敏 {
            get {
                return ResourceManager.GetString("柳艳敏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0137 的本地化字符串。
        /// </summary>
        public static string 桂晓旭 {
            get {
                return ResourceManager.GetString("桂晓旭", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0015 的本地化字符串。
        /// </summary>
        public static string 梁月 {
            get {
                return ResourceManager.GetString("梁月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0129 的本地化字符串。
        /// </summary>
        public static string 梁琳 {
            get {
                return ResourceManager.GetString("梁琳", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0079 的本地化字符串。
        /// </summary>
        public static string 梁翠芬 {
            get {
                return ResourceManager.GetString("梁翠芬", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0063 的本地化字符串。
        /// </summary>
        public static string 欧阳会意 {
            get {
                return ResourceManager.GetString("欧阳会意", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0060 的本地化字符串。
        /// </summary>
        public static string 江锡奎 {
            get {
                return ResourceManager.GetString("江锡奎", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0077 的本地化字符串。
        /// </summary>
        public static string 汤柳艳 {
            get {
                return ResourceManager.GetString("汤柳艳", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0132 的本地化字符串。
        /// </summary>
        public static string 汪云 {
            get {
                return ResourceManager.GetString("汪云", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0115 的本地化字符串。
        /// </summary>
        public static string 汪茜 {
            get {
                return ResourceManager.GetString("汪茜", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0072 的本地化字符串。
        /// </summary>
        public static string 沈苏婷 {
            get {
                return ResourceManager.GetString("沈苏婷", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0057 的本地化字符串。
        /// </summary>
        public static string 潘华锋 {
            get {
                return ResourceManager.GetString("潘华锋", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0102 的本地化字符串。
        /// </summary>
        public static string 牛义安 {
            get {
                return ResourceManager.GetString("牛义安", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0095 的本地化字符串。
        /// </summary>
        public static string 王二群 {
            get {
                return ResourceManager.GetString("王二群", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0118 的本地化字符串。
        /// </summary>
        public static string 王亭 {
            get {
                return ResourceManager.GetString("王亭", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0078 的本地化字符串。
        /// </summary>
        public static string 王兵 {
            get {
                return ResourceManager.GetString("王兵", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0160 的本地化字符串。
        /// </summary>
        public static string 王利 {
            get {
                return ResourceManager.GetString("王利", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0100 的本地化字符串。
        /// </summary>
        public static string 王和银 {
            get {
                return ResourceManager.GetString("王和银", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0113 的本地化字符串。
        /// </summary>
        public static string 王婧婧 {
            get {
                return ResourceManager.GetString("王婧婧", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0141 的本地化字符串。
        /// </summary>
        public static string 王建萍 {
            get {
                return ResourceManager.GetString("王建萍", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0084 的本地化字符串。
        /// </summary>
        public static string 王桂芝 {
            get {
                return ResourceManager.GetString("王桂芝", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0154 的本地化字符串。
        /// </summary>
        public static string 王梅 {
            get {
                return ResourceManager.GetString("王梅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0034 的本地化字符串。
        /// </summary>
        public static string 王泽丽 {
            get {
                return ResourceManager.GetString("王泽丽", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0043 的本地化字符串。
        /// </summary>
        public static string 王玉林 {
            get {
                return ResourceManager.GetString("王玉林", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0164 的本地化字符串。
        /// </summary>
        public static string 王珍 {
            get {
                return ResourceManager.GetString("王珍", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0134 的本地化字符串。
        /// </summary>
        public static string 王琼 {
            get {
                return ResourceManager.GetString("王琼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0017 的本地化字符串。
        /// </summary>
        public static string 王翠翠 {
            get {
                return ResourceManager.GetString("王翠翠", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0094 的本地化字符串。
        /// </summary>
        public static string 王贤玉 {
            get {
                return ResourceManager.GetString("王贤玉", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0044 的本地化字符串。
        /// </summary>
        public static string 王静静 {
            get {
                return ResourceManager.GetString("王静静", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0005 的本地化字符串。
        /// </summary>
        public static string 璩娟 {
            get {
                return ResourceManager.GetString("璩娟", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0009 的本地化字符串。
        /// </summary>
        public static string 盛桂华 {
            get {
                return ResourceManager.GetString("盛桂华", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0025 的本地化字符串。
        /// </summary>
        public static string 盛洁 {
            get {
                return ResourceManager.GetString("盛洁", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0101 的本地化字符串。
        /// </summary>
        public static string 祖小艳 {
            get {
                return ResourceManager.GetString("祖小艳", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0098 的本地化字符串。
        /// </summary>
        public static string 秦文 {
            get {
                return ResourceManager.GetString("秦文", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0010 的本地化字符串。
        /// </summary>
        public static string 秦正顺 {
            get {
                return ResourceManager.GetString("秦正顺", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0139 的本地化字符串。
        /// </summary>
        public static string 童珊珊 {
            get {
                return ResourceManager.GetString("童珊珊", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0049 的本地化字符串。
        /// </summary>
        public static string 管义成 {
            get {
                return ResourceManager.GetString("管义成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0061 的本地化字符串。
        /// </summary>
        public static string 管云 {
            get {
                return ResourceManager.GetString("管云", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0146 的本地化字符串。
        /// </summary>
        public static string 罗丹 {
            get {
                return ResourceManager.GetString("罗丹", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0066 的本地化字符串。
        /// </summary>
        public static string 罗翠霞 {
            get {
                return ResourceManager.GetString("罗翠霞", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0121 的本地化字符串。
        /// </summary>
        public static string 罗萍 {
            get {
                return ResourceManager.GetString("罗萍", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0028 的本地化字符串。
        /// </summary>
        public static string 耿梦媛 {
            get {
                return ResourceManager.GetString("耿梦媛", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0016 的本地化字符串。
        /// </summary>
        public static string 胡萍 {
            get {
                return ResourceManager.GetString("胡萍", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0036 的本地化字符串。
        /// </summary>
        public static string 胡超 {
            get {
                return ResourceManager.GetString("胡超", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0062 的本地化字符串。
        /// </summary>
        public static string 茆琼 {
            get {
                return ResourceManager.GetString("茆琼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0161 的本地化字符串。
        /// </summary>
        public static string 葛欣 {
            get {
                return ResourceManager.GetString("葛欣", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0177 的本地化字符串。
        /// </summary>
        public static string 蒋丽 {
            get {
                return ResourceManager.GetString("蒋丽", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0051 的本地化字符串。
        /// </summary>
        public static string 蔡卫新 {
            get {
                return ResourceManager.GetString("蔡卫新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0035 的本地化字符串。
        /// </summary>
        public static string 袁有勇 {
            get {
                return ResourceManager.GetString("袁有勇", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0074 的本地化字符串。
        /// </summary>
        public static string 袁林 {
            get {
                return ResourceManager.GetString("袁林", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0082 的本地化字符串。
        /// </summary>
        public static string 袁甜甜 {
            get {
                return ResourceManager.GetString("袁甜甜", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0097 的本地化字符串。
        /// </summary>
        public static string 许业兰 {
            get {
                return ResourceManager.GetString("许业兰", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0052 的本地化字符串。
        /// </summary>
        public static string 许劲菊 {
            get {
                return ResourceManager.GetString("许劲菊", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0046 的本地化字符串。
        /// </summary>
        public static string 许高梅 {
            get {
                return ResourceManager.GetString("许高梅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0157 的本地化字符串。
        /// </summary>
        public static string 谢梦雅 {
            get {
                return ResourceManager.GetString("谢梦雅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0069 的本地化字符串。
        /// </summary>
        public static string 费贤霞 {
            get {
                return ResourceManager.GetString("费贤霞", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0174 的本地化字符串。
        /// </summary>
        public static string 贾凡 {
            get {
                return ResourceManager.GetString("贾凡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0127 的本地化字符串。
        /// </summary>
        public static string 赵洋波 {
            get {
                return ResourceManager.GetString("赵洋波", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0111 的本地化字符串。
        /// </summary>
        public static string 迟菊 {
            get {
                return ResourceManager.GetString("迟菊", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0037 的本地化字符串。
        /// </summary>
        public static string 邓建 {
            get {
                return ResourceManager.GetString("邓建", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0126 的本地化字符串。
        /// </summary>
        public static string 邓思琦 {
            get {
                return ResourceManager.GetString("邓思琦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0114 的本地化字符串。
        /// </summary>
        public static string 邢斌 {
            get {
                return ResourceManager.GetString("邢斌", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0048 的本地化字符串。
        /// </summary>
        public static string 郑其芬 {
            get {
                return ResourceManager.GetString("郑其芬", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0178 的本地化字符串。
        /// </summary>
        public static string 郑榕 {
            get {
                return ResourceManager.GetString("郑榕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0170 的本地化字符串。
        /// </summary>
        public static string 郭梦洁 {
            get {
                return ResourceManager.GetString("郭梦洁", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0089 的本地化字符串。
        /// </summary>
        public static string 钟楠 {
            get {
                return ResourceManager.GetString("钟楠", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0021 的本地化字符串。
        /// </summary>
        public static string 闫梦 {
            get {
                return ResourceManager.GetString("闫梦", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0109 的本地化字符串。
        /// </summary>
        public static string 陈亚菲 {
            get {
                return ResourceManager.GetString("陈亚菲", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0162 的本地化字符串。
        /// </summary>
        public static string 陈凯丽 {
            get {
                return ResourceManager.GetString("陈凯丽", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0108 的本地化字符串。
        /// </summary>
        public static string 陈君 {
            get {
                return ResourceManager.GetString("陈君", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0024 的本地化字符串。
        /// </summary>
        public static string 陈新星 {
            get {
                return ResourceManager.GetString("陈新星", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0075 的本地化字符串。
        /// </summary>
        public static string 陈有珍 {
            get {
                return ResourceManager.GetString("陈有珍", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0064 的本地化字符串。
        /// </summary>
        public static string 陈润宇 {
            get {
                return ResourceManager.GetString("陈润宇", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0165 的本地化字符串。
        /// </summary>
        public static string 陈玉 {
            get {
                return ResourceManager.GetString("陈玉", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0059 的本地化字符串。
        /// </summary>
        public static string 陈道琴 {
            get {
                return ResourceManager.GetString("陈道琴", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0133 的本地化字符串。
        /// </summary>
        public static string 韩晓瑞 {
            get {
                return ResourceManager.GetString("韩晓瑞", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0067 的本地化字符串。
        /// </summary>
        public static string 韩琼 {
            get {
                return ResourceManager.GetString("韩琼", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0002 的本地化字符串。
        /// </summary>
        public static string 颜小岩 {
            get {
                return ResourceManager.GetString("颜小岩", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0128 的本地化字符串。
        /// </summary>
        public static string 马春丽 {
            get {
                return ResourceManager.GetString("马春丽", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0020 的本地化字符串。
        /// </summary>
        public static string 高丽男 {
            get {
                return ResourceManager.GetString("高丽男", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0138 的本地化字符串。
        /// </summary>
        public static string 高腊梅 {
            get {
                return ResourceManager.GetString("高腊梅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0145 的本地化字符串。
        /// </summary>
        public static string 魏雅婷 {
            get {
                return ResourceManager.GetString("魏雅婷", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0008 的本地化字符串。
        /// </summary>
        public static string 黄丽丽 {
            get {
                return ResourceManager.GetString("黄丽丽", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0163 的本地化字符串。
        /// </summary>
        public static string 黄允青 {
            get {
                return ResourceManager.GetString("黄允青", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L0030 的本地化字符串。
        /// </summary>
        public static string 黄燕云 {
            get {
                return ResourceManager.GetString("黄燕云", resourceCulture);
            }
        }
    }
}
